// signatures.js
//
// The signature database is the core IP of Theme Medic. Each entry describes the
// "code footprint" a known Shopify app leaves behind in a theme so we can detect
// it even after the app itself has been uninstalled.
//
// Matching dimensions per app:
//   - filePatterns:   regexes tested against an asset KEY (e.g. "snippets/loox.liquid",
//                     "assets/judgeme.js"). A match = the app dropped a standalone file.
//   - scriptHosts:    domains that appear inside <script src> / <link href> / fetch()
//                     URLs. A match = the app injected an external network request.
//   - markers:        regexes tested against file CONTENT — inline comment fences or
//                     liquid references the app left inside shared files like theme.liquid.
//
// `handle` is the app's Shopify App Store handle. The live app cross-references this
// against the store's list of *currently installed* apps: a signature that matches
// theme code but whose handle is NOT installed = genuine ghost code (safe-to-flag).
// A signature whose app is still installed = active code (leave it alone).

export const signatures = [
  {
    id: "loox",
    name: "Loox Product Reviews & Photos",
    handle: "loox",
    category: "reviews",
    filePatterns: [/(^|\/)loox[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["loox.io", "cdn.loox.io"],
    markers: [/loox/i],
  },
  {
    id: "judgeme",
    name: "Judge.me Product Reviews",
    handle: "judgeme",
    category: "reviews",
    filePatterns: [/(^|\/)judgeme[\w.-]*\.(liquid|js|css)$/i, /(^|\/)jdgm[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["judge.me", "cdn.judge.me", "cdnwidget.judge.me"],
    markers: [/jdgm-|judge\.me|judgeme/i],
  },
  {
    id: "yotpo",
    name: "Yotpo Reviews",
    handle: "yotpo-social-reviews",
    category: "reviews",
    filePatterns: [/(^|\/)yotpo[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["yotpo.com", "staticw2.yotpo.com", "cdn-widgetsrepository.yotpo.com"],
    markers: [/yotpo/i],
  },
  {
    id: "stamped",
    name: "Stamped Product Reviews & UGC",
    handle: "stamped-product-reviews-ugc",
    category: "reviews",
    filePatterns: [/(^|\/)stamped[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["stamped.io", "cdn-stamped-io.azureedge.net"],
    markers: [/stamped\.io|stamped-/i],
  },
  {
    id: "okendo",
    name: "Okendo Reviews",
    handle: "okendo",
    category: "reviews",
    filePatterns: [/(^|\/)okendo[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["okendo.io", "d3hw6dc1ow8pp2.cloudfront.net"],
    markers: [/okendo/i],
  },
  {
    id: "klaviyo",
    name: "Klaviyo: Email Marketing & SMS",
    handle: "klaviyo-email-marketing",
    category: "email",
    filePatterns: [/(^|\/)klaviyo[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["klaviyo.com", "static.klaviyo.com", "a.klaviyo.com"],
    markers: [/klaviyo/i],
  },
  {
    id: "privy",
    name: "Privy ‑ Pop Ups, Email, & SMS",
    handle: "privy",
    category: "popups",
    filePatterns: [/(^|\/)privy[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["privy.com", "widget.privy.com"],
    markers: [/privy/i],
  },
  {
    id: "bold-upsell",
    name: "Bold Upsell",
    handle: "product-upsell",
    category: "upsell",
    filePatterns: [/(^|\/)bold[_-]?(upsell|common|product)[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["boldapps.net", "cdn.boldapps.net"],
    markers: [/bold[_-]?upsell|boldapps/i],
  },
  {
    id: "recharge",
    name: "Recharge Subscriptions",
    handle: "subscription-payments",
    category: "subscriptions",
    filePatterns: [/(^|\/)recharge[\w.-]*\.(liquid|js|css)$/i, /(^|\/)subscription[_-]?widget[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["rechargecdn.com", "static.rechargecdn.com", "rechargepayments.com"],
    markers: [/recharge|rechargepayments/i],
  },
  {
    id: "vitals",
    name: "Vitals: All‑in‑One Marketing",
    handle: "vitals",
    category: "all-in-one",
    filePatterns: [/(^|\/)vitals[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["vitals.co", "cdn.vitals.co", "vitalstools.com"],
    markers: [/vitals\.co|vitalstools/i],
  },
  {
    id: "reconvert",
    name: "ReConvert Post Purchase Upsell",
    handle: "reconvert-upsell-cross-sell",
    category: "upsell",
    filePatterns: [/(^|\/)reconvert[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["reconvert.io", "stilylish.reconvert.io"],
    markers: [/reconvert/i],
  },
  {
    id: "smile",
    name: "Smile: Loyalty & Rewards",
    handle: "smile-rewards",
    category: "loyalty",
    filePatterns: [/(^|\/)smile[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["smile.io", "sdk.smile.io"],
    markers: [/smile\.io/i],
  },
  {
    id: "tidio",
    name: "Tidio Live Chat & AI Chatbots",
    handle: "tidio-chat",
    category: "chat",
    filePatterns: [/(^|\/)tidio[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["tidio.co", "code.tidio.co", "widget-v4.tidiochat.com"],
    markers: [/tidio/i],
  },
  {
    id: "gorgias",
    name: "Gorgias ‑ Helpdesk & Live Chat",
    handle: "gorgias-live-chat-helpdesk",
    category: "chat",
    filePatterns: [/(^|\/)gorgias[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["gorgias.chat", "config.gorgias.chat", "assets.gorgias.chat"],
    markers: [/gorgias/i],
  },
  {
    id: "pagefly",
    name: "PageFly Landing Page Builder",
    handle: "pagefly",
    category: "page-builder",
    filePatterns: [/(^|\/)pagefly[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["pagefly.io", "cdn.pagefly.io"],
    markers: [/pagefly/i],
  },
  {
    id: "shogun",
    name: "Shogun Landing Page Builder",
    handle: "shogun",
    category: "page-builder",
    filePatterns: [/(^|\/)shogun[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["getshogun.com", "f.getshogun.com"],
    markers: [/shogun/i],
  },
  {
    id: "gempages",
    name: "GemPages Landing Page Builder",
    handle: "gempages",
    category: "page-builder",
    filePatterns: [/(^|\/)gempages?[\w.-]*\.(liquid|js|css)$/i, /(^|\/)gem[_-]?page[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["gempages.net", "tools.gempages.net"],
    markers: [/gempages?/i],
  },
  {
    id: "frequently-bought-together",
    name: "Frequently Bought Together (Code Black Belt)",
    handle: "frequently-bought-together",
    category: "upsell",
    filePatterns: [/(^|\/)fbt[\w.-]*\.(liquid|js|css)$/i, /(^|\/)frequently[_-]?bought[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["selleramp.com", "cdn.codeblackbelt.com"],
    markers: [/frequently[_-]?bought|codeblackbelt/i],
  },
  {
    id: "hotjar",
    name: "Hotjar (analytics)",
    handle: "hotjar",
    category: "analytics",
    filePatterns: [/(^|\/)hotjar[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["hotjar.com", "static.hotjar.com", "script.hotjar.com"],
    markers: [/hotjar|_hjSettings/i],
  },
  {
    id: "tiktok-pixel",
    name: "TikTok Pixel",
    handle: "tiktok",
    category: "pixel",
    filePatterns: [/(^|\/)tiktok[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["analytics.tiktok.com"],
    markers: [/ttq\.load|analytics\.tiktok/i],
  },
  {
    id: "rebuy",
    name: "Rebuy Personalization Engine",
    handle: "rebuy",
    category: "upsell",
    filePatterns: [/(^|\/)rebuy[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["rebuyengine.com", "cdn.rebuyengine.com"],
    markers: [/rebuyengine|data-rebuy/i],
  },
  {
    id: "postscript",
    name: "Postscript SMS Marketing",
    handle: "postscript-sms-marketing",
    category: "email",
    filePatterns: [/(^|\/)postscript[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["postscript.io", "sdk.postscript.io"],
    markers: [/postscript\.io/i],
  },
  {
    id: "attentive",
    name: "Attentive SMS & Email",
    handle: "attentive-mobile",
    category: "email",
    filePatterns: [/(^|\/)attentive[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["attn.tv", "cdn.attn.tv"],
    markers: [/attn\.tv|attentive/i],
  },
  {
    id: "omnisend",
    name: "Omnisend Email Marketing & SMS",
    handle: "omnisend",
    category: "email",
    filePatterns: [/(^|\/)omnisend[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["omnisend.com", "omnisrc.com"],
    markers: [/omnisend/i],
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    handle: "mailchimp",
    category: "email",
    filePatterns: [/(^|\/)mailchimp[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["chimpstatic.com", "list-manage.com"],
    markers: [/mailchimp|mc4wp/i],
  },
  {
    id: "weglot",
    name: "Weglot Translate",
    handle: "weglot",
    category: "translation",
    filePatterns: [/(^|\/)weglot[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["weglot.com", "cdn.weglot.com"],
    markers: [/weglot/i],
  },
  {
    id: "langify",
    name: "langify Translation",
    handle: "langify",
    category: "translation",
    filePatterns: [/(^|\/)ly[_-]?[\w.-]*langify[\w.-]*\.(liquid|js|css)$/i, /(^|\/)langify[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: [],
    markers: [/langify|ly_languages/i],
  },
  {
    id: "swym-wishlist",
    name: "Swym Wishlist Plus",
    handle: "swym-relay",
    category: "wishlist",
    filePatterns: [/(^|\/)swym[\w.-]*\.(liquid|js|css)$/i, /(^|\/)wishlist[_-]?plus[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["swymrelay.com", "swym.it"],
    markers: [/swym/i],
  },
  {
    id: "growave",
    name: "Growave: Loyalty, Wishlist, Reviews",
    handle: "growave",
    category: "loyalty",
    filePatterns: [/(^|\/)(growave|ssw)[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["growave.io"],
    markers: [/growave|socialshopwave/i],
  },
  {
    id: "loyaltylion",
    name: "LoyaltyLion",
    handle: "loyaltylion",
    category: "loyalty",
    filePatterns: [/(^|\/)loyaltylion[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["loyaltylion.com", "sdk.loyaltylion.net"],
    markers: [/loyaltylion/i],
  },
  {
    id: "tawk",
    name: "tawk.to Live Chat",
    handle: "tawk-to",
    category: "chat",
    filePatterns: [/(^|\/)tawk[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["tawk.to", "embed.tawk.to"],
    markers: [/tawk/i],
  },
  {
    id: "intercom",
    name: "Intercom",
    handle: "intercom",
    category: "chat",
    filePatterns: [/(^|\/)intercom[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["intercom.io", "widget.intercom.io", "intercomcdn.com"],
    markers: [/intercomSettings|intercom\.io/i],
  },
  {
    id: "crisp",
    name: "Crisp Live Chat",
    handle: "crisp-chat-live-chat",
    category: "chat",
    filePatterns: [/(^|\/)crisp[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["crisp.chat", "client.crisp.chat"],
    markers: [/\$crisp|crisp\.chat/i],
  },
  {
    id: "zendesk",
    name: "Zendesk Chat / Support",
    handle: "zendesk",
    category: "chat",
    filePatterns: [/(^|\/)(zendesk|zopim)[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["zdassets.com", "zopim.com"],
    markers: [/zendesk|zopim|zE\(/i],
  },
  {
    id: "lucky-orange",
    name: "Lucky Orange Heatmaps",
    handle: "lucky-orange",
    category: "analytics",
    filePatterns: [/(^|\/)lucky[_-]?orange[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["luckyorange.com", "tools.luckyorange.com"],
    markers: [/luckyorange|__lo_site_id/i],
  },
  {
    id: "ms-clarity",
    name: "Microsoft Clarity",
    handle: "microsoft-clarity",
    category: "analytics",
    filePatterns: [/(^|\/)clarity[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["clarity.ms"],
    markers: [/clarity\.ms|window\.clarity/i],
  },
  {
    id: "meta-pixel",
    name: "Meta (Facebook) Pixel",
    handle: "facebook",
    category: "pixel",
    filePatterns: [/(^|\/)(facebook|fb)[_-]?pixel[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["connect.facebook.net"],
    markers: [/fbq\(['"]init/i],
  },
  {
    id: "pinterest-tag",
    name: "Pinterest Tag",
    handle: "pinterest",
    category: "pixel",
    filePatterns: [/(^|\/)pinterest[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["ct.pinterest.com", "s.pinimg.com"],
    markers: [/pintrk\(/i],
  },
  {
    id: "snap-pixel",
    name: "Snapchat Pixel",
    handle: "snapchat-ads",
    category: "pixel",
    filePatterns: [/(^|\/)snap[\w.-]*pixel[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["sc-static.net", "tr.snapchat.com"],
    markers: [/snaptr\(/i],
  },
  {
    id: "gtm",
    name: "Google Tag Manager / Analytics",
    handle: "google",
    category: "analytics",
    filePatterns: [/(^|\/)(gtm|google[_-]?tag)[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["googletagmanager.com", "google-analytics.com"],
    markers: [/GTM-[A-Z0-9]+|gtag\(/],
  },
  {
    id: "bing-uet",
    name: "Microsoft Ads UET Tag",
    handle: "microsoft-channel",
    category: "pixel",
    filePatterns: [],
    scriptHosts: ["bat.bing.com"],
    markers: [/uetq/i],
  },
  {
    id: "justuno",
    name: "Justuno Pop Ups & CRO",
    handle: "justuno-pop-ups-conversion",
    category: "popups",
    filePatterns: [/(^|\/)justuno[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["justuno.com", "cdn.justuno.com"],
    markers: [/justuno|ju_num/i],
  },
  {
    id: "optinmonster",
    name: "OptinMonster",
    handle: "optinmonster",
    category: "popups",
    filePatterns: [/(^|\/)optinmonster[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["optinmonster.com", "a.omappapi.com"],
    markers: [/optinmonster|omappapi/i],
  },
  {
    id: "pushowl",
    name: "PushOwl Web Push",
    handle: "pushowl",
    category: "popups",
    filePatterns: [/(^|\/)pushowl[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["pushowl.com", "cdn.pushowl.com"],
    markers: [/pushowl/i],
  },
  {
    id: "back-in-stock",
    name: "Back in Stock Alerts",
    handle: "back-in-stock",
    category: "back-in-stock",
    filePatterns: [/(^|\/)back[_-]?in[_-]?stock[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["backinstock.org", "app.backinstock.org"],
    markers: [/backinstock/i],
  },
  {
    id: "appstle",
    name: "Appstle Subscriptions",
    handle: "subscriptions-by-appstle",
    category: "subscriptions",
    filePatterns: [/(^|\/)appstle[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["appstle.com"],
    markers: [/appstle/i],
  },
  {
    id: "seal-subscriptions",
    name: "Seal Subscriptions",
    handle: "seal-subscriptions",
    category: "subscriptions",
    filePatterns: [/(^|\/)seal[_-]?subscriptions?[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["sealsubscriptions.com"],
    markers: [/sealsubscriptions|sealsubs/i],
  },
  {
    id: "fera",
    name: "Fera Product Reviews",
    handle: "fera",
    category: "reviews",
    filePatterns: [/(^|\/)fera[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["fera.ai", "cdn.fera.ai"],
    markers: [/fera\.ai|window\.fera/i],
  },
  {
    id: "ali-reviews",
    name: "Ali Reviews",
    handle: "ali-reviews",
    category: "reviews",
    filePatterns: [/(^|\/)ali[_-]?reviews?[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["alireviews.io"],
    markers: [/alireviews/i],
  },
  {
    id: "aftership",
    name: "AfterShip Tracking & Returns",
    handle: "aftership",
    category: "shipping",
    filePatterns: [/(^|\/)aftership[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["aftership.com", "cdn.aftership.com"],
    markers: [/aftership/i],
  },
  {
    id: "zipify",
    name: "Zipify Pages / OneClickUpsell",
    handle: "zipify-pages",
    category: "page-builder",
    filePatterns: [/(^|\/)zipify[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["zipify.com"],
    markers: [/zipify/i],
  },
  {
    id: "hextom",
    name: "Hextom (Ultimate Sales Boost etc.)",
    handle: "ultimate-sales-boost",
    category: "trust",
    filePatterns: [/(^|\/)hextom[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["hextom.com"],
    markers: [/hextom/i],
  },
  {
    id: "affirm",
    name: "Affirm Pay-Over-Time Messaging",
    handle: "affirm-pay-over-time-messaging",
    category: "payments",
    filePatterns: [/(^|\/)affirm[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["affirm.com", "cdn1.affirm.com"],
    markers: [/affirm\.js|_affirm_config/i],
  },
  {
    id: "sezzle",
    name: "Sezzle Widget",
    handle: "sezzle",
    category: "payments",
    filePatterns: [/(^|\/)sezzle[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["sezzle.com", "media.sezzle.com", "widget.sezzle.com"],
    markers: [/sezzle/i],
  },
  {
    id: "afterpay",
    name: "Afterpay / Clearpay Messaging",
    handle: "afterpay",
    category: "payments",
    filePatterns: [/(^|\/)(afterpay|clearpay)[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["portal.afterpay.com", "js.afterpay.com"],
    markers: [/afterpay|clearpay/i],
  },
  {
    id: "algolia",
    name: "Algolia Search & Discovery",
    handle: "algolia-search-and-discovery",
    category: "search",
    filePatterns: [/(^|\/)algolia[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["algolia.net", "algolianet.com", "cdn.jsdelivr.net/npm/algoliasearch"],
    markers: [/algolia/i],
  },
  {
    id: "searchanise",
    name: "Searchanise Search & Filter",
    handle: "searchanise",
    category: "search",
    filePatterns: [/(^|\/)searchanise[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["searchanise.io", "searchserverapi.com"],
    markers: [/searchanise/i],
  },
  {
    id: "boost-search",
    name: "Boost AI Search & Filter",
    handle: "boost-product-filter-search",
    category: "search",
    filePatterns: [/(^|\/)boost[_-]?(pfs|filter|search)[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["boostcommerce.net", "cdn.boostcommerce.net"],
    markers: [/boost-pfs|boostcommerce/i],
  },
  {
    id: "fomo",
    name: "Fomo Social Proof",
    handle: "fomo",
    category: "trust",
    filePatterns: [/(^|\/)fomo[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["fomo.com", "load.fomo.com"],
    markers: [/fomo\.com/i],
  },
  {
    id: "yotpo-smsbump",
    name: "Yotpo SMSBump",
    handle: "smsbump",
    category: "email",
    filePatterns: [/(^|\/)smsbump[\w.-]*\.(liquid|js|css)$/i],
    scriptHosts: ["smsbump.com", "cdn.smsbump.com"],
    markers: [/smsbump/i],
  },
];

// Build quick lookup helpers
export const signatureById = Object.fromEntries(signatures.map((s) => [s.id, s]));
